# Generated by Django 5.0 on 2023-12-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_description_item_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='in_stock',
            field=models.BooleanField(choices=[(0, 'Отсутствует'), (1, 'В наличии')], default=1),
        ),
    ]
