# Generated by Django 5.0 on 2024-01-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_personmodel_item_person_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmodel',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
